### ISSUE TITLE
Image upload (img2swf) not working on Windows (Cygwin/Python 2.6)

### ISSUE THREAD

**Issue by foobarlab** [foobarlab/UpStage-Video-Hack#1]
When trying to upload media on Windows (Cygwin with Python 2.6) the following error occurs:

``` text
  [exec]       0 [main] python2.6 7224 child_info_fork::abort: address space needed by 'fcntl.dll' (0x480000) is already occupied
     [exec] 2013-01-28 18:01:14+0100 [HTTPChannel,0,127.0.0.1] Unhandled Error
     [exec]     Traceback (most recent call last):
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/http.py", line 1402, in rawDataReceived
     [exec]         self._finishRequestBody(data[self.length:])
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/http.py", line 1337, in _finishRequestBody
     [exec]         self.allContentReceived()
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/http.py", line 1391, in allContentReceived
     [exec]         req.requestReceived(command, path, version)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/http.py", line 714, in requestReceived
     [exec]         self.process()
     [exec]     --- <exception caught here> ---
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/server.py", line 150, in process
     [exec]         self.render(resrc)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/web/server.py", line 157, in render
     [exec]         body = resrc.render(self)
     [exec]       File "/cygdrive/d/GIT/UpStage/build/upstage/web.py", line 455, in render
     [exec]         d = getProcessValue(config.IMG2SWF_SCRIPT, args=[swf_full, thumbnail_full] + tfns)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/internet/utils.py", line 139, in getProcessValue
     [exec]         reactor)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/internet/utils.py", line 25, in _callProtocolWithDeferred
     [exec]         reactor.spawnProcess(p, executable, (executable,)+tuple(args), env, path)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/internet/posixbase.py", line 224, in spawnProcess
     [exec]         processProtocol, uid, gid, childFDs)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/internet/process.py", line 541, in __init__
     [exec]         self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
     [exec]       File "/usr/lib/python2.6/site-packages/twisted/internet/process.py", line 372, in _fork
     [exec]         self.pid = os.fork()
     [exec]     exceptions.OSError: [Errno 11] Resource temporarily unavailable
     [exec]     
     [exec] 2013-01-28 18:01:14+0100 [HTTPChannel,0,127.0.0.1] 127.0.0.1 - - [28/Jan/2013:17:01:13 +0000] "POST /admin/save_thing HTTP/1.1" 500 52202 "http://localhost:8081/admin/workshop/mediaupload" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:18.0) Gecko/20100101 Firefox/18.0"
```

The last error visible on the webpage is:

``` text
<type 'exceptions.OSError'>: [Errno 11] Resource temporarily unavailable
```

**Comment by foobarlab** [comment]
Probably a solution: http://www.cygwin.com/ml/cygwin/2011-08/msg00205.html

**Comment by foobarlab** [comment]
Updating to Python 2.7.3 in Cygwin fixed the problem.
